import type { Metadata } from "next";
import { Alex_Brush} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const alexBrush = Alex_Brush({
    variable: "--font-alex-brush",
    weight: "400",
    style: "normal"
})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${alexBrush.variable} antialiased px-2 md:px-12 xl:px-40`}
            >
                <NavBar />
                {children}
            </body>
        </html >
    );
}
